add apdu to set and optionally freeze serial and extend length
swissbit-eis/PivApplet pull request #3
Opened 2023-03-06 14:59 UTC by swissbit-okaufmann

2023-03-07 13:55 UTC, swissbit-csteuer requested changes

2023-03-07 13:55 UTC, swissbit-csteuer commented on src/net/cooperi/pivapplet/PivApplet.java
> +	/* SwissbitPIV extensions we support */
```suggestion
	/* SwissbitPIV extensions */
```

2023-03-07 13:55 UTC, swissbit-csteuer commented on src/net/cooperi/pivapplet/PivApplet.java
> +	private boolean serialIsFreezed = false;
```suggestion
	private boolean serialIsFrozen = false;
```

2023-03-08 10:53 UTC, swissbit-okaufmann commented on src/net/cooperi/pivapplet/PivApplet.java
> +	private boolean serialIsFreezed = false;
renamed attribute

2023-03-08 10:54 UTC, swissbit-okaufmann commented on src/net/cooperi/pivapplet/PivApplet.java
> +	/* SwissbitPIV extensions we support */
done

2023-03-08 12:06 UTC, merged